version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  circleci-tests:
    description: "ci/circleci-tests only for pre-deployment"
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: C:\circle_ci_build_dir
    steps:
      - checkout
#      - run: 
#          name: "System Info"
#          command: systeminfo
#      - run:
#          name: "Check docker"
#          shell: powershell.exe
#          command: |
#            docker info
#            docker run hello-world:nanoserver-1809
      - run:
          name: "install powershell core"
          command: dotnet tool install --global PowerShell
      - run:
          name: "This is PWSH"
          command: Write-Output 'This is output'
          shell: C:\\Users\\circleci\\.dotnet\\tools\\pwsh.exe
      - run:
          name: "dir C drive"
          command: Get-ChildItem -Path 'C:\Users\circleci\.dotnet\tools'
          shell: pwsh.exe
      - run:
          name: "pscore version table"
          command: |
            pwsh.exe -Command {$PSVersionTable}
#      - run:
#          name: "Test PSCore"
#          shell: pwsh.exe
#          command: $PSVersionTable

workflows:
  build-deploy:
    jobs:
      - circleci-tests: # << the job to conditionally run based on the filter-by-branch-name.
          filters:
            branches:
              only:
                - master
                - "ci/circleci-tests"
